data_dir:
save_dir:

pose:
  pose_estimator_complexity: 1
  use_pose_estimator_over_static_image: True

video:
  frame_width: -1
  frame_height: -1
  stride: 300

inference:
  model_pth:
  infer_for: normalized_distance_matrix


